spring:
  datasource:
    url: jdbc:mysql:///<DB_NAME>?cloudSqlInstance=<INSTANCE_CONNECTION_NAME>&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: <DB_USER>
    password: <DB_PASSWORD>
#    driver-class-name: com.mysql.cj.jdbc.Driver